Seandev
justin-obrien-smoothstack/lms-angular pull request #9
Opened 2020-06-03 19:08 UTC by sean-darsie

A lot of code to pr at once. Sry guys. This is the admin author/branches and librarian code. I merged it locally with the changes that trevor made, and everything is working at the moment

2020-06-04 00:51 UTC, justin-obrien-smoothstack requested changes
As far as I can tell, the following things don't seem to do anything useful for our purposes:
- modalRef.result.then(...)
- The (onSelect) and (onSelectAll) HTML tags in the dropdown elements
- The let-d HTML tag in the modal elements
- The id HTML tags (Also, id="exampleModalLabel" gives it an appearance of having been copy-pasted.)

There shouldn't be any debugger or console.log statements in the final product.

It looks like you're having each branch object carry the full set of all book copies objects. While it's not absolutely untenable, it does cause memory use to grow quadratically with the number of database entries, which is something one would want to avoid. Resource-wise it would be better to just load a single instance of the copies, separate from the branches, although it might make coding in the librarian component a little trickier.

In the author component, after sending an HTTP call, it's best to re-load not just the authors but also the books.

Does the librarian component view dynamically update when changes are made? It doesn't look like there's any mechanism to make that happen.

If I'm not mistaken, the modal-opening functions are overwriting the forms set up by initializeFormGroup. If the validators aren't working correctly, that's probably why.

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/app.module.ts
> +  ],
Any reason for having all these commented-out components here?

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/layout/header/header.component.spec.ts
> +>>>>>>> dev
Merge conflict markers

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/librarian/librarian.component.ts
> +      .post(`${environment.libUrl}${environment.updateBanchUri}`, branch)
This should be put rather than post.

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/librarian/librarian.component.html
> +            Add Books
They can also remove books.

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/librarian/librarian.component.ts
> +        noOfCopies: obj.bookCopies.noOfCopies,
Isn't obj.bookCopies an array of bookCopies objects, and therefore the properties bookId and noOfCopies would be present on each of its elements, but not on the array itself? I don't think those properties of the form are getting initialized as intended.

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/admin/branches/branches.component.ts
> +  }
The books aren't needed by this component, unless you're planning on using them for something book-copies-related later, which I don't think would be necessary since it's already covered in the librarian component.

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/admin/author/author.component.html
> +      <th scope="row">{{ a.authorId }}</th>
We shouldn't show primary keys; you probably meant to use i+1 instead.

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/admin/branches/branches.component.ts
> +      }
These aren't used anywhere.

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/librarian/librarian.component.ts
> +          });
This doesn't seem to serve any purpose and increases memory use.

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/librarian/librarian.component.ts
> +    if (obj !== null) {
This check isn't needed for this component. obj will never be null since a branch is always passed when this function is called.

2020-06-04 00:51 UTC, justin-obrien-smoothstack commented on src/app/librarian/librarian.component.ts
> +      branchId: this.addBookCopiesForm.value.bookCopies.branchId,
Is the update copies feature working correctly? It looks like the bookId and branchId will become undefined here, and the bookId will be set to the correct value in line 189, but the branchId will remain undefined. Line 186 should probably be `branchId: this.addBookCopiesForm.value.branchId,` instead.

2020-06-04 01:08 UTC, sean-darsie commented on src/app/app.module.ts
> +  ],
I don't think they should be in the bootstrap area. They were all causing errors. I forgot to delete them.

2020-06-04 01:15 UTC, sean-darsie reviewed
The branches are not carrying around all of the books, just a list of books that are available at the library. I send that back because I think i will use if for the add/remove books feature. The branch module itself has a reference to a list of the books.

2020-06-04 01:18 UTC, sean-darsie commented on src/app/layout/header/header.component.spec.ts
> +>>>>>>> dev
I don't have those locally. That's weird. I'll try pushing the branch up again.

2020-06-04 04:09 UTC, sean-darsie commented on src/app/admin/branches/branches.component.ts
> +      }
It's used in the html

2020-06-04 15:16 UTC, justin-obrien-smoothstack commented on src/app/admin/branches/branches.component.ts
> +      }
For the author and librarian components it is. For the branch component there are no dropdowns.

2020-06-04 15:41 UTC, justin-obrien-smoothstack reviewed
Good changes

2020-06-09 03:45 UTC, sean-darsie commented on src/app/librarian/librarian.component.ts
> +      .post(`${environment.libUrl}${environment.updateBanchUri}`, branch)
fixed

2020-06-09 03:45 UTC, sean-darsie commented on src/app/librarian/librarian.component.html
> +            Add Books
resolved

2020-06-09 03:46 UTC, sean-darsie commented on src/app/librarian/librarian.component.ts
> +        noOfCopies: obj.bookCopies.noOfCopies,
I'm now getting the noOfCopies from the ui.

2020-06-09 18:01 UTC, merged